apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: dotnetserver
  namespace: kgateway-system
spec:
  parentRefs:
    - name: http
      namespace: kgateway-system
  hostnames:
    - "www.dotnetserver.com"
  rules:
    - backendRefs:
        - name: dotnetserver
          port: 5001