apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dotnetserver
  namespace: kgateway-system
spec:
  selector:
    matchLabels:
      run: dotnetserver
  template:
    metadata:
      labels:
        run: dotnetserver
    spec:
      containers:
      - name: dotnetserver
        image: varkeychanjacob/dotnetserver:amd64
        ports:
        - containerPort: 5001